config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  namespace :api, defaults: {format: :json} do
    resources :albums, only: [:create, :destroy, :index]
    resources :photos, only: [:index, :create, :destroy, :update] do
      collection do
        get 'feed'
        get 'user_photos'
      end
    end
    resources :comments, only: [:create, :index]
  end
  resources :users , only: [:new, :show, :create, :update, :index] do

  end
  resource :session, only: [:new, :create, :destroy] do
    member do
      post 'demoLogin'
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  username        :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  photo_url       :string           default("http://res.cloudinary.com/dayd3nm4v/image/upload/v1445033817/dzkg6i40xsb16orsipu8.jpg")
#

class User < ActiveRecord::Base
  attr_reader :password
  after_initialize :ensure_session_token

  validates :username,
    :email,
    :password_digest,
    :session_token,
    presence: true

  validates :username,
    :email,
    uniqueness: true

  validates :password,
    length: {minimum: 6, allow_nil: true}

  has_many :albums,
    class_name: "Album",
    foreign_key: :owner_id,
    primary_key: :id

  has_many :photos,
    through: :albums,
    source: :photos

  has_many :comments,
    class_name: "Comment",
    foreign_key: :user_id,
    primary_key: :id



  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    return BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    #get 2 featured users
    if current_user != nil
      id  = current_user.id
      @users = User.where(
        "id != #{id}").order('random()').limit(2).includes(:photos, :albums)
    else
      @users = User.order('random()').limit(2).includes(:photos, :albums)
    end
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = current_user
    render :show
  end

  def update
    url = params[:user][:photo_url]
    current_user.update!(photo_url: url)
    render json: current_user
  end


  private
  def user_params
    params.require(:user).permit(:password, :username, :email, :photo_url)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="loginPage">
  <div class="loginBox">
    <div class="loginLogo"><img src="/logo2.png"/></div>
    <h1>Create an Account!</h1>
    <form  action="<%= users_url %>" method="post">
      <%= auth_token_input %>
      <%= flash[:errors].join("<br>").html_safe if flash[:errors] %><br/><br/>
      <label class="email">
        Email &nbsp;
      </label>
        <input type="text" name="user[email]" value="">
      <br/>
      <label class="password">
        Password &nbsp;
      </label>
      <input type="password" name="user[password]" value="">
      <br/>
      <label >
        Username &nbsp;
      </label>
        <input type="text"  name="user[username]" value="">

      <input type="submit"  value="Sign Up" id="signupButton">
    </form>
    <form action="<%= new_session_url %>" method="get">
      <%= auth_token_input %>
      <input type="submit"
             name="name"
             value="Have an account? or enter as guest",
             id="redirect">
    </form>
  </div>
</div>